### PR TITLE
skills & causes min/max fixed

### PR DESCRIPTION
**Pull request by nibab-boo**
- [x] min 1 and max 5 for passions/social causes fixed
- [x] min 1 and max 10 for skills fixed
- [x] make chip box take all remaining space.

While changing for the chip box, I had to change onboarding pseudo-box. So, I had to modify every step of onboarding process. But, This onboarding box doesn't overflow from screen. 
Please, let me know if I need to change something or if there is anything, you didn't like.

### CODE REVIEW

**Comment by lalomartins** [comment]
Just one more fix on that topic 🙏 the submit buttons for those two pages are enabled when you arrive on the step, even though nothing is selected. If you try to click them, they disable. They should start off disabled already.

**Comment by nibab-boo** [comment]
This change should do it. Previous change was redundant. For max, function is checking it before inserting.

**Comment by lalomartins** [comment]
hmm, but I think we should also prevent the user from going forward if they select more than 5, because just showing the error in the end makes it much harder to fill everything correctly. Also I don't think we even have logic to go to a previous page.

Unrelated, but in the latest preview of this branch I can't see which ones are selected anymore

**Comment by nibab-boo** [comment]
Sorry. I was working fine. Not sure, but probably because of cache.  I will fix it. 
Lalo, what should we do if user select max options???
Show error?? or do nothing??.

**Comment by lalomartins** [comment]
Show error is ok. If it's not too much work, though, it would be even better to block selecting more once you have max.

**Comment by nibab-boo** [comment]
Selected issue was from main.  Blocking selection after is already there. Like, it doesn't select new one once Max is reached.

**Comment by lalomartins** [comment]
awesome. The selected issue probably came from Hadis' branch 😅 but we still have to fix it anyway otherwise I can't test this 😉

**Comment by nibab-boo** [comment]
I already fixed it. I should be working now.

**Comment by lalomartins** [comment]
Looks good now, thanks.

So sorry 😹 but I found a different bug today. Copying from the ticket.

> One more issue: on the phone number step, the country drop-down doesn’t let me select anything other than Japan. It should allow any country, and default to the country I set earlier as my country.

**Comment by nibab-boo** [comment]
Lalo. I tried to do it. But, there were few issues with it.

1. Google places doesn't return country phone code. -> So, I used a different free API and was able to retrieve the code per country.
2. The plugin that we are using doesn't allow us to show custom values. So, default and number showing is not working. 
Like, country code are selected in background. But, it doesn't allow us to show it in same field.

**Comment by lalomartins** [comment]
Better, thanks. Nice find with the free api. But the width of the country code drop down makes it unreadable.

- Please make it display the code, not the country name, when the drop-down is not expanded (e.g. +81)
- Make it wide enough that it can show a 3-digit number; doesn't matter for now if that makes it different from figma
- Default it to the same country we entered before

**Comment by nibab-boo** [comment]
Okay. I will try with it after making a pull request for signup fix.

**Comment by nibab-boo** [comment]
@lalomartins I used different plugins. But, Have build issues in cloudflare.

**Comment by lalomartins** [comment]
> @lalomartins I used different plugins. But, Have build issues in cloudflare.

Yes, it looks like a conflict in package requirements. Let me take a look, I think we just need to update some stuff.

**Comment by nibab-boo** [comment]
Also, there is some issue with the layout(figma). But I included those because it was related to Mozhde's work.

**Comment by lalomartins** [comment]
> Also, there is some issue with the layout(figma) after merging main. But I included those because it was related to Mozhde's work.

what kind of issue? where?

**Comment by lalomartins** [comment]
btw one quick thing while I'm testing — we can remove the first page, as we found it's redundant with the last of signup

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
