### PR TITLE
chore: switch user and org profile

### PR DESCRIPTION
**Pull request by bastantebom**
This PR will enable user switching from org and profile

For all related actions that require display of current identity.
Need to execute get identities then find the current identity.

https://user-images.githubusercontent.com/5590282/189871790-62eef218-d40a-4e8e-b788-6a07de47f755.mov

### CODE REVIEW

**Comment by lalomartins** [comment]
Looks good, but I suggest you integrate it inside the `useUser` hook instead, since the user profile isn't really useful in itself without the identity. In fact, maybe `useUser` should return *only* the current identity instead, as that's what we want most of the time? 🤔

**Comment by bastantebom** [comment]
> Looks good, but I suggest you integrate it inside the `useUser` hook instead, since the user profile isn't really useful in itself without the identity. In fact, maybe `useUser` should return _only_ the current identity instead, as that's what we want most of the time? 🤔

I ended up adding identities list and currentIdentity on the useUser hook and make `user` as dynamic value `user or org`

**Comment by lalomartins** [comment]
sorry for my conflict mess 😹 hopefully it will be for the best though 🙏

**Comment by bastantebom** [comment]
> sorry for my conflict mess 😹 hopefully it will be for the best though 🙏

no worries,

**Pull request merged**
