### PR TITLE
Feat/manage org

### PR DESCRIPTION
**Pull request by narges22**

### CODE REVIEW

**Review by lalomartins — CHANGES_REQUESTED** [review]
@narges22 some of these icons should be HeroIcons (maybe all). We already have the kebab menu button on other pages, you can check that code

**Comment by narges22** [comment]
> @narges22 some of these icons should be HeroIcons (maybe all). We already have the kebab menu button on other pages, you can check that code

@lalomartins I found menu icon so I removed my icon and pushed the code. I couldn't find any of the other icons :(

**Comment by narges22** [comment]
> also I would like to see actual communication with the BE

can I have the api documentation. swagger file or postman?

**Comment by lalomartins** [comment]
sure, it's here: https://dev.socious.io/api/doc/apidoc/#api-Organazation.Members

**Review by lalomartins — CHANGES_REQUESTED** [review]
Hi @narges22 . The code is quite good! Can you try using SWR for the get requests like we're using everywhere? Thanks

**Comment by lalomartins** [comment]
Also there's a build error. To see and debug those without having access to CloudFlare, what you can do is run `npm run build` locally and see if it passes.

**Comment by narges22** [comment]
> Also there's a build error. To see and debug those without having access to CloudFlare, what you can do is run `npm run build` locally and see if it passes.

yeah, I did run the command, but there is no local error.

**Comment by lalomartins** [comment]
@narges22 here's the error. Maybe it's something you forgot to add to git, or something you removed and left a lingering reference behind.
image

**Comment by narges22** [comment]
> @narges22 here's the error. Maybe it's something you forgot to add to git, or something you removed and left a lingering reference behind.
> image

thanks @lalomartins. I think it was because of the alias(@) in the path that causes error, I fixed it and used heroIcons.
btw I encountered this issue before in build Time and found a solution to revert aliases into relative import while building the app.. there are few packages that can be used

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
