### PR TITLE
Feature/babo/u12.1 submitting work for review

### PR DESCRIPTION
**Pull request by nibab-boo**
- [x] Implemented different modals.
- [x] Banner
- [x] Implemented hired project pages for user
- [x] Implemented hired(mission) page for user
- [x] Implemented mission api for submitting and canceling work.

### CODE REVIEW

**Comment by lalomartins** [comment]
@nibab-boo I think we converted this to draft because we wanted to wait for the Mission refactoring, now that the API has changed, can you check if this code needs changes, and submit again?

**Comment by lalomartins** [comment]
@nibab-boo please handle this branch before working on something else

**Comment by nibab-boo** [comment]
@lalomartins I will do it today. But, before that, I will need to ask Eshan to populate my user with some offers and missions.

**Comment by nibab-boo** [comment]
@lalomartins , Finally it is done.

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
