### PR TITLE
626-one on one chat

### PR DESCRIPTION
**Pull request by nibab-boo**
- [x]  View recent messages(This was already implemented in the previous ticket to test different screens and responsiveness.)
- [x]  Send message
- [x]  Load older messages on the scroll

My concern related to this is the date to be shown on chat. What should be the ideal way or diff to group the messages???
Plz, let me know if there is something you want me to do on this.

### CODE REVIEW

**Comment by lalomartins** [comment]
There's a build error, please check.

For your question, I think it goes something like this:

- store previous message in state
- loop over messages (map() or whatever) to display them
- before the actual message component: `if message.date != previousMessage.date showDate()` (pseudocode)

This logic should work even with `flex-col-reverse`, the only difference is which date you show (if order is normal you'd show message.date but if reversed you show previousMessage.date).

**Comment by nibab-boo** [comment]
- [ ] Added date/time into chat
- [ ] Refactored infinite scrolling

**Comment by lalomartins** [comment]
Oh, there's one more requirement I forgot to include in the ticket. When you view the chat, we want to mark the newest message as read using the [read](https://dev.socious.io/api/doc/apidoc/#api-Chat-read_Messages) endpoint. Doing that should also rerender the blue dot with the number of unread messages in the chat list.

**Comment by nibab-boo** [comment]
@lalomartins  Sorry for the trouble. This one should be good to go if you find no bugs/problems. But, plz let me know if something passed through my radar.

**Comment by nibab-boo** [comment]
I think it is doing something on that line but, not sure if it is a perfect solution.
Plz check it and let me know what you think of this.

**Comment by lalomartins** [comment]
You only need to call `read` once, for the latest message

**Comment by lalomartins** [comment]
One more minor thing while you're fixing the read thing: when writing a message, pressing enter should send it

**Comment by nibab-boo** [comment]
Right now, I am calling `read` only once if there is an unread_message. But, I am also calling on message successfully send because it was showing as unread when reloaded.

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
