### PR TITLE
Fixed avatar, filter and new chat screen

### PR DESCRIPTION
**Pull request by nibab-boo**
- [x] Avatar added to commentItem
- [x] Filter using BE endpoint?filter
- [x] Fixed New chat screen.

@lalomartins I added avatar to commentItem. But, I am not sure if this is where you meant by `missing avatar`. If not, plz let me know.

### CODE REVIEW

**Comment by lalomartins** [comment]
> @lalomartins I added avatar to commentItem. But, I am not sure if this is where you meant by `missing avatar`. If not, plz let me know.

No, that would be part of the next ticket. I mean in the list of chats, each chat should show the avatar of the other participant.

But actually you have implemented that already. What's missing is only in the case when the other participant is an organization, you need to use `image` instead of `avatar`.

**Comment by nibab-boo** [comment]
I haven't seen an org schema. So, I will try to created one and check it.

**Comment by lalomartins** [comment]
I'm still not getting the Socious logo in my chats. I think possibly you're doing the check in the wrong places.
image

**Comment by nibab-boo** [comment]
@lalomartins, I fixed those. Let me know if you want any other changes.

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
