### PR TITLE
Babo/auth/responsive

### PR DESCRIPTION
**Pull request by nibab-boo**
Responsive Auth.
- [x] Sign Up
- [x] Sign In
- [x] Forgot Password
- [x] Change Password

For onboarding, did it on the same onboarding branch.

### CODE REVIEW

**Review by lalomartins — CHANGES_REQUESTED** [review]
Mostly good, but the vertical alignment is a little off. It needs more space on top. Check different sizes and presets in the responsive menu when testing 🙏 
image
image
image

**Comment by nibab-boo** [comment]
@lalomartins. Here is the fix for those. Could you check this out??

localhost_3000_auth_login(Socious Mobile)
localhost_3000_(Socious Mobile)
localhost_3000_auth_signup(Socious Mobile)

**Comment by nibab-boo** [comment]
Build errors are coming from other files. I am not sure if I should temper with those since someone might be working on them.

**Comment by lalomartins** [comment]
yes the build won't work on any branch that hasn't merged my fixes. I think let's first merge your forgotpassword PR, then you can again merge main into this one and fix conflicts, and then we can test and merge this?

**Comment by nibab-boo** [comment]
Okay. Got it.

**Comment by lalomartins** [comment]
btw, all the other stuff has been merged already, you can update this and the other one

**Comment by nibab-boo** [comment]
I will need to refactor with `forgot-password` branch.

**Comment by nibab-boo** [comment]
I think we had this back-arrow (< ) for step 1 in only mobile-design so, I added that for both.
But, new code from main was hiding it. And, I refactored with main(making it hidden)
Except that, it should be good to go.

**Review by lalomartins — APPROVED** [review]

**Pull request merged**
