### PR TITLE
Non-registered users - prompt to register to apply to projects

### PR DESCRIPTION
**Pull request by nehawork**

### CODE REVIEW

**Comment by seira-yun** [comment]
@lalomartins Could you review @nehawork 's work, please?

**Comment by seira-yun** [comment]
@lalomartins why is it closed?

**Comment by lalomartins** [comment]
I think we discussed it on slack, the implementation is not according to the design. Since I haven't heard from this in more than a week, I don't know if it's still being worked on, keeping the pending PR in the list could cause confusion now that we're asking for more people to help with reviews

**Comment by lalomartins** [comment]
If it's still being worked on, she can reopen or open a new one when ready. If it goes to someone else instead, well, there is probably not enough work here to reuse, they might as well start from scratch

**Comment by seira-yun** [comment]
@lalomartins make sense.

@nehawork 
Could you give us updates?

**Pull request closed without merging**
