### PR TITLE
fix forgot password, and:

### PR DESCRIPTION
**Pull request by lalomartins**
- add a toast
- redirect to home
- update password validation to same as signup

### CODE REVIEW

**Comment by nibab-boo** [comment]
Worked perfectly when I tried it.

**Comment by lalomartins** [comment]
> Worked perfectly when I tried it.

then give it an approve please 😸

**Comment by nibab-boo** [comment]
It seems I don't have the right to do that.

**Comment by lalomartins** [comment]
> It seems I don't have the right to do that.

can you check now?

**Pull request merged**
